name: Main CI

on: [push]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.1
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        apk add gcc musl-dev libffi-dev
        pip install poetry
    - name: Run Tests
      run: |
        poetry run tests
